## Porto Seguro's Feature Engineering and Exploration

In [2]:
import numpy as np
import pandas as pd
import os

In [8]:
# Data
path= r"D:\My Computer\DATA\Porto_Seguros" #Windows
#path= r"/Users/nicapotato/Desktop/Data/House" #Mac

# Load, combine, save index, delete excess data from memory
train_df = pd.read_csv(open(os.path.join(path, "train.csv"), "r"), index_col='id')
test_df = pd.read_csv(open(os.path.join(path, "test.csv"), "r"), index_col='id')
print(train_df.shape, test_df.shape)
label = train_df['target'].copy()
train_df = train_df.drop('target', axis=1)
traindex = train_df.index
testdex = test_df.index
df = pd.concat([train_df,test_df])
del train_df
del test_df

(595212, 58) (892816, 57)

In [9]:
df.head()

,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
id,,,,,,,,,,,,,,,,,,,,,
7,2,2,5,1,0,0,1,0,0,0,...,9,1,5,8,0,1,1,0,0,1
9,1,1,7,0,0,0,0,1,0,0,...,3,1,1,9,0,1,1,0,1,0
13,5,4,9,1,0,0,0,1,0,0,...,4,2,7,7,0,1,1,0,1,0
16,0,1,2,0,0,1,0,0,0,0,...,2,2,4,9,0,0,0,0,0,0
17,0,2,0,1,0,1,0,0,0,0,...,3,1,1,3,0,0,0,1,1,0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1488028 entries, 7 to 1488026
Data columns (total 57 columns):
ps_ind_01         1488028 non-null int64
ps_ind_02_cat     1488028 non-null int64
ps_ind_03         1488028 non-null int64
ps_ind_04_cat     1488028 non-null int64
ps_ind_05_cat     1488028 non-null int64
ps_ind_06_bin     1488028 non-null int64
ps_ind_07_bin     1488028 non-null int64
ps_ind_08_bin     1488028 non-null int64
ps_ind_09_bin     1488028 non-null int64
ps_ind_10_bin     1488028 non-null int64
ps_ind_11_bin     1488028 non-null int64
ps_ind_12_bin     1488028 non-null int64
ps_ind_13_bin     1488028 non-null int64
ps_ind_14         1488028 non-null int64
ps_ind_15         1488028 non-null int64
ps_ind_16_bin     1488028 non-null int64
ps_ind_17_bin     1488028 non-null int64
ps_ind_18_bin     1488028 non-null int64
ps_reg_01         1488028 non-null float64
ps_reg_02         1488028 non-null float64
ps_reg_03         1488028 non-null float64
ps_car_01_cat     1488028 non-null int64
ps_car_02_cat     1488028 non-null int64
ps_car_03_cat     1488028 non-null int64
ps_car_04_cat     1488028 non-null int64
ps_car_05_cat     1488028 non-null int64
ps_car_06_cat     1488028 non-null int64
ps_car_07_cat     1488028 non-null int64
ps_car_08_cat     1488028 non-null int64
ps_car_09_cat     1488028 non-null int64
ps_car_10_cat     1488028 non-null int64
ps_car_11_cat     1488028 non-null int64
ps_car_11         1488028 non-null int64
ps_car_12         1488028 non-null float64
ps_car_13         1488028 non-null float64
ps_car_14         1488028 non-null float64
ps_car_15         1488028 non-null float64
ps_calc_01        1488028 non-null float64
ps_calc_02        1488028 non-null float64
ps_calc_03        1488028 non-null float64
ps_calc_04        1488028 non-null int64
ps_calc_05        1488028 non-null int64
ps_calc_06        1488028 non-null int64
ps_calc_07        1488028 non-null int64
ps_calc_08        1488028 non-null int64
ps_calc_09        1488028 non-null int64
ps_calc_10        1488028 non-null int64
ps_calc_11        1488028 non-null int64
ps_calc_12        1488028 non-null int64
ps_calc_13        1488028 non-null int64
ps_calc_14        1488028 non-null int64
ps_calc_15_bin    1488028 non-null int64
ps_calc_16_bin    1488028 non-null int64
ps_calc_17_bin    1488028 non-null int64
ps_calc_18_bin    1488028 non-null int64
ps_calc_19_bin    1488028 non-null int64
ps_calc_20_bin    1488028 non-null int64
dtypes: float64(10), int64(47)
memory usage: 658.5 MB

In [13]:
df.describe(include=['O'])

ValueError: No objects to concatenate